Repository TechnionYP5779/team1-bot, pull requests merged in 2018-12, with the labels that each got.

#20 Feature/filter courses
  .classpath
  spartanizer.xml
  src/main/java/FuncTest/TestFunc/Function.java
  src/main/java/FuncTest/TestFunc/globals.java
  src/main/java/FuncTest/TestFunc/utils.java
Labels: needs review

#39 Feature/courses postrequisites
  src/main/java/FuncTest/TestFunc/Function.java
  src/main/java/FuncTest/TestFunc/globals.java
  src/main/java/FuncTest/TestFunc/utils.java
  src/main/java/postrequsites/Course.java
  src/main/java/postrequsites/PostrequisiteDBGenerator.java
  src/main/java/postrequsites/PostrequisiteHandler.java
  src/main/java/responses/TableResponse.java
Labels: needs review

#53 Feature/courses prerequisites
  .classpath
  src/main/java/FuncTest/TestFunc/Function.java
  src/main/java/FuncTest/TestFunc/globals.java
  src/main/java/FuncTest/TestFunc/utils.java
  src/test/java/FuncTest/TestFunc/HttpResponseMessageMock.java
Labels: needs review

#40 Inserted all courses to Courses DB #15
  .classpath
  .settings/org.eclipse.jdt.core.prefs
  CourseDesc.json
  courseInfo.csv
  courseInfo.json
  pom.xml
  src/main/java/Utils/JsonReader.java
  src/main/java/Utils/SimpleWebParser.java
  src/main/java/course/info/CourseObject.java
  src/main/java/course/info/DataToDBLoader.java
  src/main/java/course/info/WebInfoExtractor.java
  src/test/java/course/info/DataToDBLoaderTest.java
  src/test/java/course/info/WebInfoExtractorTest.java
Labels: needs review

#55 Feature/index and search courses
  spartanizer.xml
  src/main/java/homework/HomeworkGetter.java
  src/main/java/indexer/Bag.java
  src/main/java/indexer/Descriptions.txt
  src/main/java/indexer/Indexer.java
  src/main/java/indexer/output.txt
  src/main/java/indexer/query.txt
  src/main/java/indexer/stopwords.txt
  src/main/java/indexer/test.txt
Labels: needs review

#60 Feature/video info
  Technion - Video Server Courses List.html
  old_server_videos.csv
  parse.py
  spartanizer.xml
  src/main/java/FuncTest/TestFunc/Function.java
  src/main/java/FuncTest/TestFunc/VideoAnswers.java
  src/main/java/FuncTest/TestFunc/globals.java
  src/main/java/course/info/DataToDBLoader.java
  src/main/java/insertDataToDB/CSVPusher.java
  src/main/java/insertDataToDB/old_server_videos.csv
  src/main/java/old_server_videos.csv
  src/main/java/postrequsites/PostrequisiteDBGenerator.java
  src/main/java/postrequsites/PostrequisiteHandler.java
  tokens/StoredCredential
Labels: needs review

#63 removed all warnings
  src/main/java/indexer/Bag.java
  src/main/java/indexer/Indexer.java
  src/main/java/postrequsites/PostrequisiteHandler.java
Labels: needs review

#47 Feature/google tasks api
  .gitignore
  pom.xml
  src/main/java/google/tasks/GoogleTasksAPI.java
  src/main/java/google/tasks/TaskBuilder.java
  src/main/java/google/tasks/azureCred.json
  src/main/java/google/tasks/credentials.json
Labels: feature

#52 Feature/login subscribe runRules
  src/main/java/FuncTest/TestFunc/Function.java
  src/main/java/FuncTest/TestFunc/globals.java
  src/main/java/homework/HomeworkGetter.java
  src/main/java/rule/RunRulesHandler.java
  src/main/java/rule/loginHandler.java
  src/main/java/rule/subscribeHandler.java
Labels: Bot Rule System
